import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { execSync } from 'node:child_process';
process.env.DATA_DIR = mkdtempSync(path.join(tmpdir(), 'dbg2-dd-'));
const { WebSocket } = await import('ws');
const { startMockSsh, makeFixture } = await import('./test/mock-ssh-server.js');
const { startApp } = await import('./server/index.js');
const ROOT = mkdtempSync(path.join(tmpdir(), 'dbg2-root-'));
makeFixture(ROOT);
const mock = startMockSsh({ port: 2322, rootDir: ROOT });
const { server } = await startApp({ port: 4222, host: '127.0.0.1', quiet: true });
const ws = new WebSocket('ws://127.0.0.1:4222/ws');
await new Promise((res, rej) => { ws.on('open', res); ws.on('error', rej); });
const send = (m) => ws.send(JSON.stringify(m));
const req = (m) => new Promise((res) => { const id = Math.random().toString(36).slice(2); ws.send(JSON.stringify({ ...m, reqId: id })); const h = (raw) => { const mm = JSON.parse(raw.toString()); if (mm.reqId === id) { ws.off('message', h); res(mm); } }; ws.on('message', h); });
const countOrphans = () => execSync('wmic process where "name=\'node.exe\'" get ProcessId,CommandLine', { encoding: 'utf8' }).split('\n').filter(l => l.trim().startsWith('node') && l.includes('setInterval')).length;
console.log('orphans before:', countOrphans());
await req({ type: 'connect', ssh: { host: '127.0.0.1', port: 2322, username: 'tester', auth: { type: 'password', password: 'pass' }, autoReconnect: true } });
await new Promise((r) => setTimeout(r, 300));
await req({ type: 'set_workspace', path: '/src' });
send({ type: 'run_command', command: 'node -e "setInterval(()=>{},1000)"' });
await new Promise((r) => setTimeout(r, 600));
console.log('orphans while running:', countOrphans());
// 获取 runId
const started = await new Promise((res) => { const h = (raw) => { const m = JSON.parse(raw.toString()); if (m.type === 'exec' && m.event === 'start') { ws.off('message', h); res(m); } }; ws.on('message', h); });
send({ type: 'stop_command', runId: started.runId });
await new Promise((r) => setTimeout(r, 1500));
console.log('orphans after stop:', countOrphans());
server.close(); mock.close(); process.exit(0);
